name: Fix Typo or Error
description: Fix typo(s) or error(s) in RDF and HTML documents
title: "[FIX]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: checkboxes
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification is affected by this
      options:
        - label: DPV
        - label: Personal Data (PD)
        - label: Technical (TECH)
        - label: Locations (LOC)
        - label: RISK
        - label: AI
        - label: Justifications
        - label: LEGAL (e.g. IE, US)
        - label: EU-GDPR
        - label: EU-DGA
        - label: EU-NIS2
        - label: EU-AIAct
        - label: EU-Rights
    validations:
      required: true
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: Please list all typo(s), error(s), etc. here
      placeholder: Errors can be typo(s), missing or broken links, missing images, wrong references, incorrect attributions...
      value: Fix ...
    validations:
      required: true
