name: How to use DPV for...?
description: Ask question(s) for how to use DPV for a specific application
title: "[HOW]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to participate!
  - type: checkboxes
    id: specs
    attributes:
      label: Specs
      description: Please indicate which specification the question is about
      options:
        - label: DPV
        - label: Personal Data (PD)
        - label: Technical (TECH)
        - label: Locations (LOC)
        - label: RISK
        - label: AI
        - label: Justifications
        - label: LEGAL (e.g. IE, US)
        - label: EU-GDPR
        - label: EU-DGA
        - label: EU-NIS2
        - label: EU-AIAct
        - label: EU-Rights
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What is the question or suggestion?
      value: ...
    validations:
      required: true
